### ISSUE TITLE
[NEW-ALGORITHM]

### ISSUE THREAD

**Issue by MonkD3** [Siddhesh-Agarwal/Python-Algorithms#1]
1. **Name of Algorithm**: Explicit Euler method for EDO
2. **Type of Algorithm**: Mathematics (numerical computation)
3. **Source Code**:
```py

import numpy as np
def euler_ode(a, b, u0, n_step,  f):
    """
    solve the ODE given by : 
              u'(x) = f(x, u(x))    with  a <= x <= b
              u(a) = u0

    Parameters
    =======
    a  [float] : starting x value.
    b [float] : ending x value.
    u0 [float] : initial condition.
    n_step : number of step used to compute the result.
    f [function of 2 parameters] : function describing the ODE as given above.
    u [function of 1 parameter] 

    Returns 
    =====
    np.ndarray : an array of size n_step describing the solution of the ODE in the range [a, b].

    Example
    =====
    If we have the simple equation : u'(x) = - u(x) with u(a) = u0,
    and we want to know the value of u in the range [a,b]
    We just have to call : euler_edo(a, b, u0, (b-a)*10, lambda x, u : -u)
    """
    x, step = np.linspace(a, b, n_step + 1, retstep = True)
    u = np.zeros(len(x))
    u[0] = u0

    for i in range(len(x) - 1):
        u[i+1] = u[i] + step*f(x, u[i])

    return u
```

What this algorithm does is solving the ordinary differential equation step by step. This is the simplest of the Taylor's method, also called the Euler Explicit method. It works in a really neat manner : 
1. It approximate the derivative of the function at x.
2. It makes a small step in the direction of the derivative.
3. Return to point 1 with x + step

This is usually the first numerical method involving ODE's teached to students.

**Comment by Siddhesh-Agarwal** [comment]
Thank you for suggesting the algorithm. I have added the code snippet to the website.
